import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, LegalSection } from "@/components/legal-page";

export const Route = createFileRoute("/privacy-policy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | iMOX Copilot" },
      { name: "description", content: "How iMOX Copilot collects, uses, and protects data." },
    ],
  }),
  component: PrivacyPolicy,
});

function PrivacyPolicy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      updated="14 March 2026"
      intro={
        <p>
          iMOX Copilot respects your privacy and is committed to protecting your personal data. This
          Privacy Policy explains how we collect, use, and safeguard your information when you use
          our platform.
        </p>
      }
    >
      <LegalSection number="01" title="Data Controller">
        <p>The controller responsible for data processing is:</p>
        <div className="rounded-xl border border-border bg-secondary/70 p-5">
          <p className="font-bold text-brand-ink">Dib GmbH</p>
          <p>In den Birken 34</p>
          <p>42113, Wuppertal</p>
          <p>Germany</p>
          <p className="mt-3">
            Email:{" "}
            <a
              className="font-semibold text-primary hover:underline"
              href="mailto:info@dib-holding.com"
            >
              info@dib-holding.com
            </a>
          </p>
        </div>
      </LegalSection>
      <LegalSection number="02" title="Data We Collect">
        <p>We may collect the following types of data:</p>
        <div className="grid gap-3 sm:grid-cols-3">
          {[
            ["Account Data", "Name", "Phone number", "Email address", "Profile picture"],
            [
              "Usage Data",
              "Messages sent within iMOX",
              "Tasks generated by the system",
              "Interaction with features",
            ],
            ["Technical Data", "IP address", "Device type", "Operating system", "Browser type"],
          ].map(([title, ...items]) => (
            <div key={title} className="rounded-xl border border-border bg-background p-4">
              <p className="mb-3 text-[10px] font-bold uppercase tracking-[0.18em] text-muted-foreground">
                {title}
              </p>
              {items.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </div>
          ))}
        </div>
      </LegalSection>
      <LegalSection number="03" title="Purpose of Data Processing">
        <p>We process personal data to:</p>
        <ul className="list-disc space-y-2 pl-5 marker:text-primary">
          <li>Provide the iMOX platform</li>
          <li>Enable team collaboration</li>
          <li>Automatically convert messages into tasks</li>
          <li>Improve product performance</li>
          <li>Ensure platform security</li>
          <li>Provide customer support</li>
        </ul>
      </LegalSection>
      <LegalSection number="04" title="Legal Basis (GDPR)">
        <p>Processing is based on:</p>
        <ul className="list-disc space-y-2 pl-5 marker:text-primary">
          <li>
            <strong className="text-brand-ink">Art. 6(1)(b) GDPR</strong> - Contractual necessity
          </li>
          <li>
            <strong className="text-brand-ink">Art. 6(1)(f) GDPR</strong> - Legitimate interest
          </li>
          <li>
            <strong className="text-brand-ink">Art. 6(1)(a) GDPR</strong> - Consent where applicable
          </li>
        </ul>
      </LegalSection>
      <LegalSection number="05" title="Data Storage">
        <p>
          Your data is stored on secure servers within the European Union or with trusted cloud
          providers complying with GDPR.
        </p>
      </LegalSection>
      <LegalSection number="06" title="Data Sharing">
        <p>
          <strong className="text-brand-ink">We do not sell personal data.</strong>
        </p>
        <p>Data may be shared with:</p>
        <ul className="list-disc space-y-2 pl-5 marker:text-primary">
          <li>Cloud infrastructure providers</li>
          <li>Analytics providers</li>
          <li>Payment processors, if applicable</li>
        </ul>
        <p>All partners are bound by data protection agreements.</p>
      </LegalSection>
      <LegalSection number="07" title="Data Retention">
        <p>
          We retain personal data only as long as necessary to provide the service or comply with
          legal obligations.
        </p>
      </LegalSection>
      <LegalSection number="08" title="Your Rights">
        <p>Under GDPR you have the right to:</p>
        <ul className="list-disc space-y-2 pl-5 marker:text-primary">
          <li>Access your data</li>
          <li>Correct inaccurate data</li>
          <li>Request deletion</li>
          <li>Restrict processing</li>
          <li>Data portability</li>
          <li>Object to processing</li>
        </ul>
        <p>
          To exercise your rights contact:{" "}
          <a
            className="font-semibold text-primary hover:underline"
            href="mailto:privacy@imox-app.com"
          >
            privacy@imox-app.com
          </a>
        </p>
      </LegalSection>
      <LegalSection number="09" title="Security">
        <p>
          We implement technical and organizational measures to protect your data against
          unauthorized access, loss, or misuse.
        </p>
      </LegalSection>
      <LegalSection number="10" title="Changes">
        <p>We may update this policy from time to time. Updates will be published on this page.</p>
      </LegalSection>
      <div className="rounded-xl border border-border bg-secondary/70 p-5 text-sm leading-7 text-muted-foreground">
        <p className="font-bold text-brand-ink">Questions about your privacy?</p>
        <p>
          Reach our privacy team at{" "}
          <a
            className="font-semibold text-primary hover:underline"
            href="mailto:privacy@imox-app.com"
          >
            privacy@imox-app.com
          </a>{" "}
          or the data controller at{" "}
          <a
            className="font-semibold text-primary hover:underline"
            href="mailto:info@dib-holding.com"
          >
            info@dib-holding.com
          </a>
          .
        </p>
      </div>
    </LegalPage>
  );
}
